- assignment: a82c86ed788d337c1b234c44de3a5e4d
  section: "Making Sprites w/ p5.game.js"
  paths: [ ]
- assignment: a82c86ed788d337c1b234c44de3a5e4d
  section: "Adding asteroids to the game"
  paths: [ ]
- assignment: a82c86ed788d337c1b234c44de3a5e4d
  section: "Collision detection"
  paths: [ ]